# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('language', models.CharField(max_length=50)),
                ('codeSnippet', models.TextField(max_length=2000)),
                ('description', models.TextField(max_length=2000)),
                ('author', models.CharField(max_length=100)),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
